// Data for Color Aquatic Blog
console.log('data.js loaded');

// Danh sách bài viết (chung cho cả hai ngôn ngữ, file path sẽ được thay đổi dựa trên ngôn ngữ)
const posts = [
    {
        id: 'tep-mau',
        titleVi: 'Tép Màu (Neocaridina) - Hướng dẫn nuôi và chăm sóc',
        titleEn: 'Color Shrimp (Neocaridina) - Care and Breeding Guide',
        date: '2024-01-20',
        descriptionVi: 'Tìm hiểu về tép màu (Neocaridina) - nhóm tép cảnh phổ biến nhất với nhiều màu sắc đa dạng như đỏ, vàng, xanh, cam. Hướng dẫn cách nuôi và chăm sóc để chúng phát triển khỏe mạnh.',
        descriptionEn: 'Learn about color shrimp (Neocaridina) - the most popular group of aquarium shrimp with diverse colors like red, yellow, blue, orange. Guide on how to care and breed them for healthy development.',
        keywordsVi: 'tép màu, neocaridina, tép cherry, tép cảnh màu sắc, nuôi tép màu',
        keywordsEn: 'color shrimp, neocaridina, cherry shrimp, colorful aquarium shrimp, keeping color shrimp'
    },
    {
        id: 'tep-lanh',
        titleVi: 'Tép Lạnh - Hướng dẫn nuôi và chăm sóc',
        titleEn: 'Cold Water Shrimp - Care Guide',
        date: '2024-01-18',
        descriptionVi: 'Tìm hiểu về tép lạnh - nhóm tép có thể sống ở nhiệt độ thấp, không cần máy sưởi. Phù hợp với khí hậu mát mẻ và giúp tiết kiệm điện.',
        descriptionEn: 'Learn about cold water shrimp - a group of shrimp that can live at low temperatures without a heater. Suitable for cool climates and helps save electricity.',
        keywordsVi: 'tép lạnh, tép amano, tép ghost, nuôi tép không cần sưởi, tép ôn đới',
        keywordsEn: 'cold water shrimp, amano shrimp, ghost shrimp, shrimp without heater, temperate shrimp'
    },
    {
        id: 'tep-sulawesi',
        titleVi: 'Tép Sulawesi - Hướng dẫn nuôi và chăm sóc',
        titleEn: 'Sulawesi Shrimp - Care Guide',
        date: '2024-01-16',
        descriptionVi: 'Tìm hiểu về tép Sulawesi - nhóm tép quý hiếm và đặc biệt từ Indonesia. Yêu cầu điều kiện nuôi đặc biệt với nhiệt độ cao và pH cao.',
        descriptionEn: 'Learn about Sulawesi shrimp - rare and special shrimp group from Indonesia. Requires special care conditions with high temperature and high pH.',
        keywordsVi: 'tép sulawesi, tép cardinal, tép quý hiếm, nuôi tép sulawesi, caridina dennerli',
        keywordsEn: 'sulawesi shrimp, cardinal shrimp, rare shrimp, keeping sulawesi shrimp, caridina dennerli'
    },
    {
        id: 'setup-be-tep',
        titleVi: 'Hướng dẫn Setup Bể Tép Cảnh Cho Người Mới Bắt Đầu',
        titleEn: 'Aquarium Shrimp Setup Guide for Beginners',
        date: '2024-01-10',
        descriptionVi: 'Hướng dẫn chi tiết cách setup bể tép cảnh từ A-Z, bao gồm lựa chọn thiết bị, setup môi trường nước và các lưu ý quan trọng.',
        descriptionEn: 'Detailed guide on how to setup an aquarium shrimp tank from A-Z, including equipment selection, water environment setup and important notes.',
        keywordsVi: 'setup bể tép, bể tép cảnh, hướng dẫn nuôi tép',
        keywordsEn: 'shrimp tank setup, aquarium shrimp tank, shrimp keeping guide'
    }
];

const collectionProducts = [
    {
        id: 'tep-bluedream',
        category: 'shrimps',
        nameVi: 'Tép Blue Dream',
        nameEn: 'Blue Dream Shrimp',
        shortDescriptionVi: 'Tép cảnh với màu xanh dương tuyệt đẹp, phù hợp cho người chơi lâu năm.',
        shortDescriptionEn: 'Beautiful blue-colored aquarium shrimp, suitable for experienced hobbyists.',
        temperature: '22-26°C',
        tds: '150-250 ppm',
        gh: '6-12 dGH',
        lifespan: '1-2',
        images: ['bluedream1.png', 'bluedream2.png', 'bluedream3.png', 'bluedream4.png']
    },
    {
        id: 'tep-pure-red-line',
        category: 'shrimps',
        nameVi: 'Tép Pure Red Line',
        nameEn: 'Pure Red Line Shrimp',
        shortDescriptionVi: 'Tép với đường màu đỏ thuần khiết, màu sắc sống động và bền vững.',
        shortDescriptionEn: 'Shrimp with pure red lines, vibrant and sustainable colors.',
        temperature: '20-28°C',
        tds: '120-200 ppm',
        gh: '4-10 dGH',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-blue-diamond',
        category: 'shrimps',
        nameVi: 'Tép Blue Diamond',
        nameEn: 'Blue Diamond Shrimp',
        shortDescriptionVi: 'Tép cảnh với màu xanh kim cương lấp lánh, dễ nuôi cho người mới.',
        shortDescriptionEn: 'Diamond-blue colored shrimp with sparkling beauty, easy for beginners.',
        temperature: '20-26°C',
        tds: '150-300 ppm',
        gh: '4-8 dGH',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-cam',
        category: 'shrimps',
        nameVi: 'Tép Cam',
        nameEn: 'Orange Shrimp',
        shortDescriptionVi: 'Tép màu cam rực rỡ, dễ nuôi và giá cả phải chăng.',
        shortDescriptionEn: 'Vibrant orange shrimp, easy to keep and affordable.',
        temperature: '18-25°C',
        tds: '150-350 ppm',
        gh: '3-15 dGH',
        lifespan: '1-1.5',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-bloody-mary',
        category: 'shrimps',
        nameVi: 'Tép Bloody Mary',
        nameEn: 'Bloody Mary Shrimp',
        shortDescriptionVi: 'Tép cao cấp với màu đỏ thẫm và đầu trong suốt độc đáo.',
        shortDescriptionEn: 'Premium shrimp with deep red color and unique transparent head.',
        temperature: '20-24°C',
        tds: '150-250 ppm',
        gh: '4-8 dGH',
        lifespan: '1.5-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-snow-ball',
        category: 'shrimps',
        nameVi: 'Tép Snow Ball',
        nameEn: 'Snow Ball Shrimp',
        shortDescriptionVi: 'Tép trắng tinh như tuyết, tạo điểm nhấn đẹp trong bể cây xanh.',
        shortDescriptionEn: 'Pure white snow-like shrimp, beautiful accent in planted tanks.',
        temperature: '18-26°C',
        tds: '150-350 ppm',
        gh: '4-12 dGH',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-black-galaxy-fishbone-snowflake',
        category: 'shrimps',
        nameVi: 'Tép Black Galaxy Fishbone Snowflake',
        nameEn: 'Black Galaxy Fishbone Snowflake Shrimp',
        shortDescriptionVi: 'Tép lạnh cao cấp với họa tiết thiên hà đen và tuyết rơi.',
        shortDescriptionEn: 'Premium cold-water shrimp with black galaxy and snowflake patterns.',
        temperature: '20-24°C',
        tds: '90-150 ppm',
        gh: '3-6 dGH',
        lifespan: '2-3',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-black-galaxy-boa',
        category: 'shrimps',
        nameVi: 'Tép Black Galaxy BOA',
        nameEn: 'Black Galaxy BOA Shrimp',
        shortDescriptionVi: 'Vua của các loại tép lạnh với vẻ đẹp tuyệt đỉnh và giá trị cực cao.',
        shortDescriptionEn: 'The king of cold-water shrimp with ultimate beauty and extreme value.',
        temperature: '18-22°C',
        tds: '80-120 ppm',
        gh: '2-5 dGH',
        lifespan: '3-4',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'tep-red-galaxy-tiger',
        category: 'shrimps',
        nameVi: 'Tép Red Galaxy Tiger',
        nameEn: 'Red Galaxy Tiger Shrimp',
        shortDescriptionVi: 'Tép lạnh với màu đỏ rực rỡ, họa tiết sọc hổ và chấm galaxy.',
        shortDescriptionEn: 'Cold-water shrimp with vibrant red, tiger stripes and galaxy spots.',
        temperature: '20-24°C',
        tds: '100-160 ppm',
        gh: '3-6 dGH',
        lifespan: '2-2.5',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    // Sample fishes products
    {
        id: 'ca-betta',
        category: 'fishes',
        nameVi: 'Cá Betta (Xiêm)',
        nameEn: 'Betta Fish (Siamese Fighter)',
        shortDescriptionVi: 'Cá Betta với màu sắc rực rỡ và dễ nuôi, phù hợp cho người mới bắt đầu.',
        shortDescriptionEn: 'Vibrant and easy-to-care Betta fish, perfect for beginners.',
        temperature: '24-28°C',
        tds: '150-300 ppm',
        gh: '5-19 dGH',
        lifespan: '2-3',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'ca-guppy',
        category: 'fishes',
        nameVi: 'Cá Guppy',
        nameEn: 'Guppy Fish',
        shortDescriptionVi: 'Cá Guppy nhỏ xinh với màu sắc đa dạng, sinh sản nhanh và dễ chăm sóc.',
        shortDescriptionEn: 'Small colorful Guppy fish, fast breeding and easy care.',
        temperature: '22-28°C',
        tds: '150-400 ppm',
        gh: '7-12 dGH',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    // Sample accessory products
    {
        id: 'may-loc-nuoc',
        category: 'accessory',
        nameVi: 'Máy Lọc Nước Mini',
        nameEn: 'Mini Water Filter',
        shortDescriptionVi: 'Máy lọc nước nhỏ gọn phù hợp cho bể nano, duy trì chất lượng nước tốt.',
        shortDescriptionEn: 'Compact water filter suitable for nano tanks, maintains good water quality.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'den-led-thuy-sinh',
        category: 'accessory',
        nameVi: 'Đèn LED Thủy Sinh',
        nameEn: 'LED Aquarium Light',
        shortDescriptionVi: 'Đèn LED chuyên dụng cho thủy sinh, hỗ trợ quang hợp và tăng màu sắc.',
        shortDescriptionEn: 'Specialized LED light for aquariums, supports photosynthesis and enhances colors.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '3-5',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    // New accessory products
    {
        id: 'loc-qs200',
        category: 'accessory',
        nameVi: 'Lọc QS200',
        nameEn: 'QS200 Filter',
        shortDescriptionVi: 'Combo lọc vi sinh cao cấp từ Qanvee, tích hợp công nghệ denitrate khử nitrat hiệu quả.',
        shortDescriptionEn: 'Premium biological filtration combo from Qanvee with advanced denitrate technology for effective nitrate removal.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '2-3',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'loc-thac-kaokui',
        category: 'accessory',
        nameVi: 'Lọc thác Kaokui',
        nameEn: 'Kaokui Waterfall Filter',
        shortDescriptionVi: 'Hệ thống lọc treo ngoài với thiết kế thác nước độc đáo, model KK-528 và KK-538.',
        shortDescriptionEn: 'Hang-on-back filtration system with unique waterfall design, models KK-528 and KK-538.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '2-3',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'keo-dan-reu-thuy-sinh',
        category: 'accessory',
        nameVi: 'Keo dán rêu thủy sinh',
        nameEn: 'Aquatic Moss Glue',
        shortDescriptionVi: 'Keo GUO Elephant Super Glue chuyên dụng cho việc dán rêu và cây thủy sinh, an toàn sinh học.',
        shortDescriptionEn: 'GUO Elephant Super Glue specially designed for attaching moss and aquatic plants, biologically safe.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'binh-co2-thuy-sinh',
        category: 'accessory',
        nameVi: 'Bình CO2 thủy sinh',
        nameEn: 'Aquatic CO2 Tank',
        shortDescriptionVi: 'Thiết bị cung cấp carbon dioxide cho cây thủy sinh, thúc đẩy quá trình quang hợp.',
        shortDescriptionEn: 'Carbon dioxide supply device for aquatic plants, promoting photosynthesis process.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '3-5',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'loc-vang-kaokui',
        category: 'accessory',
        nameVi: 'Lọc váng Kaokui',
        nameEn: 'Kaokui Surface Skimmer',
        shortDescriptionVi: 'Thiết bị KK-88 Surface Skimmer Mini chuyên loại bỏ váng dầu và tạp chất nổi.',
        shortDescriptionEn: 'KK-88 Surface Skimmer Mini device specialized in removing oil film and floating debris.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '2-3',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'den-neo-helios',
        category: 'accessory',
        nameVi: 'Đèn Neo-Helios',
        nameEn: 'Neo-Helios Light',
        shortDescriptionVi: 'Đèn LED RGB 3 in 1 cao cấp với công nghệ Solar Light, thiết kế phẳng hiện đại.',
        shortDescriptionEn: 'Premium RGB LED 3-in-1 light with Solar Light technology and modern flat design.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '5-7',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'men-vi-sinh-koika-bac',
        category: 'accessory',
        nameVi: 'Men vi sinh Koika-Bac',
        nameEn: 'Koika-Bac Microorganisms',
        shortDescriptionVi: 'Sản phẩm bổ sung men vi sinh chuyên dụng, giúp phân hủy chất thải và cân bằng sinh học.',
        shortDescriptionEn: 'Specialized probiotic supplement that helps decompose waste and maintain biological balance.',
        temperature: 'N/A',
        tds: 'N/A',
        gh: 'N/A',
        lifespan: '1-2',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    // Plants products
    {
        id: 'reu-pelia',
        category: 'plants',
        nameVi: 'Rêu Pelia',
        nameEn: 'Pelia Moss',
        shortDescriptionVi: 'Rêu thủy sinh độc đáo với hình dạng giống lá gan, tốc độ phát triển chậm nhưng tạo hiệu ứng thị giác đẹp mắt.',
        shortDescriptionEn: 'Unique aquatic liverwort with leaf-like appearance, slow growth but creates stunning visual effects.',
        temperature: '18-26°C',
        tds: 'N/A',
        gh: 'Soft to medium',
        lifespan: 'N/A',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'reu-mini-taiwan',
        category: 'plants',
        nameVi: 'Rêu Mini Taiwan',
        nameEn: 'Mini Taiwan Moss',
        shortDescriptionVi: 'Rêu thủy sinh có kích thước rất nhỏ, tạo thảm xanh dày đặc và đẹp mắt cho foreground.',
        shortDescriptionEn: 'Very small aquatic moss that creates dense, beautiful green carpets for foreground planting.',
        temperature: '22-28°C',
        tds: 'N/A',
        gh: 'Soft to hard',
        lifespan: 'N/A',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'duong-xi-chau-phi',
        category: 'plants',
        nameVi: 'Dương Xỉ Châu Phi',
        nameEn: 'African Fern',
        shortDescriptionVi: 'Dương xỉ nước với lá kép chia thùy sâu, độc đáo và dễ chăm sóc trong aquascape.',
        shortDescriptionEn: 'Aquatic fern with compound, deeply divided leaves, unique and easy to care for in aquascaping.',
        temperature: '20-28°C',
        tds: 'N/A',
        gh: 'Soft to medium',
        lifespan: 'N/A',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'duong-xi-la-kim-mini',
        category: 'plants',
        nameVi: 'Dương Xỉ Lá Kim Mini',
        nameEn: 'Mini Needle Leaf Fern',
        shortDescriptionVi: 'Biến thể đặc biệt của dương xỉ Java với lá hẹp dài như kim, tạo hiệu ứng động trong nước.',
        shortDescriptionEn: 'Special Java Fern variant with narrow needle-like leaves, creating dynamic effects in water.',
        temperature: '18-30°C',
        tds: 'N/A',
        gh: 'Soft to hard',
        lifespan: 'N/A',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    },
    {
        id: 'ray-nana',
        category: 'plants',
        nameVi: 'Ráy Nana',
        nameEn: 'Anubias Nana',
        shortDescriptionVi: 'Cây thủy sinh phổ biến và dễ trồng nhất với lá xanh đậm bóng, hoàn hảo cho người mới.',
        shortDescriptionEn: 'Most popular and easy-to-grow aquatic plant with dark green glossy leaves, perfect for beginners.',
        temperature: '22-28°C',
        tds: 'N/A',
        gh: 'Soft to hard',
        lifespan: 'N/A',
        images: ['placeholder1.png', 'placeholder2.png', 'placeholder3.png', 'placeholder4.png']
    }
];